# E-mail to use in cert generation
email: "noreply@provectus.com"

# AWS IAM credentials
accessKeyID: ""
secretAccessKey: ""

# AWS Region
region: ""

# (optional) Route53 zone ID for managed zone
hostedZoneID: ""

# (optional) Namespace for secret holding secretAccessKey
secretNamespace: cert-manager
