"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "aws-alb-ingress-controller"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "ingress-system"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "aws-alb-ingress-controller"
    "helm":
      "parameters":
      - "name": "rbac.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::245582572290:role/kf-example_aws-alb-ingress-controller"
      - "name": "clusterName"
        "value": "kf-example"
      - "name": "awsVpcID"
        "value": "vpc-08b8d8ca2e40371f1"
      - "name": "awsRegion"
        "value": "us-east-2"
      - "name": "resources.limits.cpu"
        "value": "100m"
      - "name": "resources.limits.memory"
        "value": "300Mi"
      - "name": "resources.requests.cpu"
        "value": "100m"
      - "name": "resources.requests.memory"
        "value": "300Mi"
    "repoURL": "https://kubernetes-charts-incubator.storage.googleapis.com"
    "targetRevision": "1.0.2"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
