{{- $hostedZoneID := .Values.hostedZoneID | default "" -}}

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53:
            region: {{ .Values.region }}
            accessKeyID: {{ .Values.accessKeyID }}
            secretAccessKeySecretRef:
              name: route53-config
              key: secret-access-key
{{- if ne $role "" }}
              role: {{ .Values.role }}
{{- end}}              
{{- if ne $hostedZoneID "" }}
            hostedZoneID: {{ .Values.hostedZoneID }}
{{- end}}

---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: {{ .Values.region }}
            accessKeyID: {{ .Values.accessKeyID }}
            secretAccessKeySecretRef:
              name: route53-config
              key: secret-access-key
{{- if ne $role "" }}
              role: {{ .Values.role }}
{{- end}}                
{{- if ne $hostedZoneID "" }}
            hostedZoneID: {{ .Values.hostedZoneID }}
{{- end}}
