securityContext:
  runAsNonRoot: true
  fsGroup: 1000

env:
  AWS_REGION: ${aws_region}
  AWS_DEFAULT_REGION: ${aws_region}
  POLLER_INTERVAL_MILLISECONDS: ${poller_interval}

serviceAccount:
  annotations: 
    eks.amazonaws.com/role-arn: ${aws_assume_role_arn}
  
fullnameOverride: external-secrets
