"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "kube-prometheus"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "monitoring"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "kube-prometheus"
    "helm":
      "parameters":
      - "name": "alertmanager.enabled"
        "value": "true"
      - "name": "namespace"
        "value": "monitoring"
      - "name": "operator.enabled"
        "value": "true"
      - "name": "prometheus.disableCompaction"
        "value": "true"
      - "name": "prometheus.enableAdminAPI"
        "value": "true"
      - "name": "prometheus.enabled"
        "value": "true"
      - "name": "prometheus.externalLabels.cluster"
        "value": "kubeflow"
      - "name": "prometheus.ingress.certManager"
        "value": "true"
      - "name": "prometheus.ingress.enabled"
        "value": "false"
      - "name": "prometheus.ingress.hostname"
        "value": "prometheus.kubeflow.edu.provectus.io"
      - "name": "prometheus.ingress.tls"
        "value": "true"
      - "name": "prometheus.persistence.enabled"
        "value": "true"
      - "name": "prometheus.persistence.size"
        "value": "10Gi"
      - "name": "prometheus.retention"
        "value": "10d"
      - "name": "prometheus.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::245582572290:role/kubeflow_thanos"
      - "name": "prometheus.serviceAccount.name"
        "value": "thanos"
      - "name": "prometheus.thanos.create"
        "value": "true"
      - "name": "prometheus.thanos.ingress.certManager"
        "value": "true"
      - "name": "prometheus.thanos.ingress.enabled"
        "value": "false"
      - "name": "prometheus.thanos.ingress.hosts[0]"
        "value": "thanos-gateway.kubeflow.edu.provectus.io"
      - "name": "prometheus.thanos.ingress.tls[0].hosts[0]"
        "value": "thanos-gateway.kubeflow.edu.provectus.io"
      - "name": "prometheus.thanos.ingress.tls[0].secretName"
        "value": "thanos-gateway-local-tls"
      - "name": "prometheus.thanos.objectStorageConfig.secretKey"
        "value": "objstore.yml"
      - "name": "prometheus.thanos.objectStorageConfig.secretName"
        "value": "thanos-objstore-config"
    "repoURL": "https://charts.bitnami.com/bitnami"
    "targetRevision": "6.1.1"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
