"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "ingress-nginx"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "ingress-system"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "ingress-nginx"
    "helm":
      "parameters":
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-additional-resource-tags"
        "value": "environment=dev,project=EDUCATION"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-backend-protocol"
        "value": "http"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-cert"
        "value": "arn:aws:acm:eu-north-1:245582572290:certificate/3bf81d87-d76b-4eb2-8ec5-dd8970db894d"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-ssl-ports"
        "value": "https"
      - "name": "controller.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-type"
        "value": "nlb"
      - "name": "controller.service.targetPorts.http"
        "value": "http"
      - "name": "controller.service.targetPorts.https"
        "value": "http"
      - "name": "rbac.create"
        "value": "true"
      - "name": "resources.limits.cpu"
        "value": "100m"
      - "name": "resources.limits.memory"
        "value": "300Mi"
      - "name": "resources.requests.cpu"
        "value": "100m"
      - "name": "resources.requests.memory"
        "value": "300Mi"
    "repoURL": "https://kubernetes.github.io/ingress-nginx"
    "targetRevision": "2.16.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
