"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "kube-prometheus-stack"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "monitoring"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "kube-prometheus-stack"
    "helm":
      "parameters":
      - "name": "alertmanager.enabled"
        "value": "true"
      - "name": "grafana.adminPassword"
        "value": "KMS_ENC:AQICAHgOE1EODon3pKNDF0fUj1NnTBLpYhGnNkfugfqqvne+XAGjjT4+uZY4wsSonfPfoBfNAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuRO5DWzlLVgjDeJIAgEQgCvZgnnu8ivT+4JquZhiUZ9VHZRnIH8ulDIeqvn77QNNJqGKCWB+iTNbOi6K:"
      - "name": "grafana.allowed.domains"
        "value": "local"
      - "name": "grafana.enabled"
        "value": "true"
      - "name": "grafana.google.auth"
        "value": "false"
      - "name": "grafana.ingress.enabled"
        "value": "true"
      - "name": "grafana.ingress.hosts[0]"
        "value": "grafana.swiss-army-grusakov.edu.provectus.io"
      - "name": "grafana.pvc.enabled"
        "value": "true"
      - "name": "namespace"
        "value": "monitoring"
      - "name": "prometheus.enabled"
        "value": "true"
      - "name": "prometheus.ingress.enabled"
        "value": "false"
      - "name": "rbac.create"
        "value": "true"
      - "name": "resources.limits.cpu"
        "value": "100m"
      - "name": "resources.limits.memory"
        "value": "300Mi"
      - "name": "resources.requests.cpu"
        "value": "100m"
      - "name": "resources.requests.memory"
        "value": "300Mi"
    "repoURL": "https://prometheus-community.github.io/helm-charts"
    "targetRevision": "12.8.0"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
